import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'contactPage',
  title: 'Contact Page',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero Section'},
    {name: 'form', title: 'Inquiry Form'},
    {name: 'direct', title: 'Direct Contact'},
  ],
  fields: [
    defineField({
      group: 'hero',
      name: 'heroImage',
      title: 'Hero Image',
      type: 'cloudinary.asset',
    }),
    defineField({
      group: 'hero',
      name: 'heading',
      title: 'Heading',
      type: 'string',
      description: 'e.g. Tell us about your day.',
      initialValue: 'Tell us about your day.',
    }),
    defineField({
      group: 'hero',
      name: 'subheading',
      title: 'Subheading',
      type: 'text',
      rows: 2,
    }),
    defineField({
      group: 'form',
      name: 'formHeading',
      title: 'Inquiry Form Heading',
      type: 'string',
      initialValue: 'Send an Inquiry',
    }),
    defineField({
      group: 'direct',
      name: 'directHeading',
      title: '"Reach Us Directly" Heading',
      type: 'string',
      initialValue: 'Reach us directly',
    }),
    defineField({
      group: 'direct',
      name: 'email',
      title: 'Contact Email',
      type: 'string',
      description: 'Shown in the "reach us directly" block. Falls back to Site Settings.',
    }),
    defineField({
      group: 'direct',
      name: 'phone',
      title: 'Contact Phone',
      type: 'string',
      description: 'Falls back to Site Settings.',
    }),
    defineField({
      group: 'direct',
      name: 'address',
      title: 'Studio Address',
      type: 'string',
      description: 'Falls back to Site Settings.',
    }),
    defineField({
      name: 'formName1Label',
      title: 'Form: Name Label',
      type: 'string',
      group: 'form',
      initialValue: 'Your name',
    }),
    defineField({
      name: 'formName1Placeholder',
      title: 'Form: Name Placeholder',
      type: 'string',
      group: 'form',
      initialValue: 'Ananya',
    }),
    defineField({
      name: 'formName2Label',
      title: "Form: Partner's Name Label",
      type: 'string',
      group: 'form',
      initialValue: "Partner's name",
    }),
    defineField({
      name: 'formName2Placeholder',
      title: "Form: Partner's Name Placeholder",
      type: 'string',
      group: 'form',
      initialValue: 'Rohan',
    }),
    defineField({
      name: 'formEmailLabel',
      title: 'Form: Email Label',
      type: 'string',
      group: 'form',
      initialValue: 'Email address',
    }),
    defineField({
      name: 'formEmailPlaceholder',
      title: 'Form: Email Placeholder',
      type: 'string',
      group: 'form',
      initialValue: 'you@email.com',
    }),
    defineField({
      name: 'formPhoneLabel',
      title: 'Form: Phone Label',
      type: 'string',
      group: 'form',
      initialValue: 'Mobile number',
    }),
    defineField({
      name: 'formPhonePlaceholder',
      title: 'Form: Phone Placeholder',
      type: 'string',
      group: 'form',
      initialValue: '+91 00000 00000',
    }),
    defineField({
      name: 'formDateLabel',
      title: 'Form: Wedding Date Label',
      type: 'string',
      group: 'form',
      initialValue: 'Wedding date',
    }),
    defineField({
      name: 'formDatePlaceholder',
      title: 'Form: Wedding Date Placeholder',
      type: 'string',
      group: 'form',
      initialValue: 'e.g. 14 Feb 2027',
    }),
    defineField({
      name: 'formCityLabel',
      title: 'Form: City Label',
      type: 'string',
      group: 'form',
      initialValue: 'City / venue',
    }),
    defineField({
      name: 'formCityPlaceholder',
      title: 'Form: City Placeholder',
      type: 'string',
      group: 'form',
      initialValue: 'Hyderabad',
    }),
    defineField({
      name: 'formInterestLabel',
      title: 'Form: Interested-in Label',
      type: 'string',
      group: 'form',
      initialValue: 'Interested in',
    }),
    defineField({
      name: 'interestPhotoLabel',
      title: 'Interest Option: Photography',
      type: 'string',
      group: 'form',
      initialValue: 'Photography only',
    }),
    defineField({
      name: 'interestFilmsLabel',
      title: 'Interest Option: Films',
      type: 'string',
      group: 'form',
      initialValue: 'Films only',
    }),
    defineField({
      name: 'interestBothLabel',
      title: 'Interest Option: Both',
      type: 'string',
      group: 'form',
      initialValue: 'Photography + Films',
    }),
    defineField({
      name: 'formMessageLabel',
      title: 'Form: Message Label',
      type: 'string',
      group: 'form',
      initialValue: 'A little about your wedding',
    }),
    defineField({
      name: 'formMessagePlaceholder',
      title: 'Form: Message Placeholder',
      type: 'string',
      group: 'form',
      initialValue: 'Functions, guest count, what matters most to you...',
    }),
    defineField({
      name: 'submitLabel',
      title: 'Submit Button Label',
      type: 'string',
      group: 'form',
      initialValue: 'SUBMIT INQUIRY',
    }),
    defineField({
      name: 'submitSendingLabel',
      title: 'Submit Button: Sending State',
      type: 'string',
      group: 'form',
      initialValue: 'SENDING...',
    }),
    defineField({
      name: 'submitSentLabel',
      title: 'Submit Button: Sent State',
      type: 'string',
      group: 'form',
      initialValue: 'SENT - THANK YOU',
    }),
    defineField({
      name: 'emailLabel',
      title: 'Direct: Email Label',
      type: 'string',
      group: 'direct',
      initialValue: 'Email',
    }),
    defineField({
      name: 'phoneLabel',
      title: 'Direct: Phone Label',
      type: 'string',
      group: 'direct',
      initialValue: 'Phone / Whatsapp',
    }),
    defineField({
      name: 'instagramLabel',
      title: 'Direct: Instagram Label',
      type: 'string',
      group: 'direct',
      initialValue: 'Instagram',
    }),
    defineField({
      name: 'instagramHandle',
      title: 'Direct: Instagram Handle Text',
      type: 'string',
      group: 'direct',
      initialValue: '@dknottphotography',
    }),
    defineField({
      name: 'locationNote',
      title: 'Direct: Location Note',
      type: 'string',
      group: 'direct',
      initialValue: 'Based in India, available worldwide.',
    }),
    defineField({
      name: 'mapEmbedUrl',
      title: 'Map Embed URL',
      type: 'text',
      rows: 3,
      group: 'direct',
      description: 'The Google Maps embed link (iframe src) for the studio location.',
    }),
  ],
})
