import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'universePage',
  title: 'Universe Page',
  type: 'document',
  groups: [
    {name: 'intro', title: 'Intro Overlay'},
    {name: 'hints', title: 'Darkroom Hints'},
    {name: 'lightbox', title: 'Photo Lightbox'},
    {name: 'reels', title: 'Reels (Categories)'},
  ],
  fields: [
    defineField({
      group: 'intro',
      name: 'title',
      title: 'Page Title',
      type: 'string',
      description: 'e.g. Unrehearsed',
      initialValue: 'Unrehearsed',
    }),
    defineField({
      group: 'intro',
      name: 'description',
      title: 'Subtitle',
      type: 'text',
      rows: 2,
      description: 'e.g. candid photography, still on the reel',
      initialValue: 'candid photography, still on the reel',
    }),
    defineField({
      group: 'reels',
      name: 'categories',
      title: 'Categories',
      type: 'array',
      description:
        'Renames the Universe reels (Street / Nature / Portrait). The "id" must stay one of: street, nature, portrait — only change the display title. Leave the array empty to keep the built-in labels.',
      of: [
        defineField({
          name: 'category',
          title: 'Category',
          type: 'object',
          fields: [
            defineField({
              name: 'id',
              title: 'Category ID',
              type: 'string',
              description: 'Must be street, nature or portrait.',
              options: {list: ['street', 'nature', 'portrait']},
            }),
            defineField({
              name: 'title',
              title: 'Display Title',
              type: 'string',
              description: 'e.g. Street',
            }),
          ],
        }),
      ],
    }),
    defineField({
      name: 'enterLabel',
      title: 'Enter Button Label',
      type: 'string',
      group: 'intro',
      description: 'Button that opens the darkroom.',
      initialValue: 'step into the darkroom',
    }),
    defineField({
      name: 'contactLabel',
      title: 'Contact Link Label',
      type: 'string',
      group: 'intro',
      initialValue: 'Alpha — get in touch',
    }),
    defineField({
      name: 'hintDrag',
      title: 'Hint: Drag',
      type: 'string',
      group: 'hints',
      initialValue: 'drag to look around',
    }),
    defineField({
      name: 'hintScroll',
      title: 'Hint: Scroll',
      type: 'string',
      group: 'hints',
      initialValue: 'scroll to move closer',
    }),
    defineField({
      name: 'hintClick',
      title: 'Hint: Click Reel',
      type: 'string',
      group: 'hints',
      initialValue: 'click a reel to open it',
    }),
    defineField({
      name: 'backLabel',
      title: 'Back Link Label',
      type: 'string',
      group: 'hints',
      initialValue: '← back to the reels',
    }),
    defineField({
      name: 'loadingLabel',
      title: 'Loading Text',
      type: 'string',
      group: 'hints',
      initialValue: 'loading the darkroom…',
    }),
    defineField({
      name: 'storyPlaceholder',
      title: 'Photo Story Placeholder',
      type: 'string',
      group: 'lightbox',
      description: 'Caption hint shown under an opened photo.',
      initialValue: 'a one-line story for this frame goes here — where it was shot, or why it stuck with you',
    }),
    defineField({
      name: 'closeLabel',
      title: 'Close Button Label',
      type: 'string',
      group: 'lightbox',
      initialValue: 'close',
    }),
  ],
})
